### ISSUE TITLE
"Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by tlambrou** [lotas/contentful-graph-web#1]
This looks like an amazing tool, but unfortunately I am getting the following error/trace...

```
Unhandled Rejection: Promise: Promise {
  <rejected> TypeError: Cannot read property 'name' of undefined
    at getTypeName (/opt/app/node_modules/contentful-graph/src/get-relations.js:13:66)
    at Array.map (<anonymous>)
    at relations.(anonymous function).(anonymous function).validations.reduce (/opt/app/node_modules/contentful-graph/src/get-relations.js:23:56)
    at Array.reduce (<anonymous>)
    at addRelation (/opt/app/node_modules/contentful-graph/src/get-relations.js:21:49)
    at contentType.fields.forEach.field (/opt/app/node_modules/contentful-graph/src/get-relations.js:39:7)
    at Array.forEach (<anonymous>)
    at getRelations (/opt/app/node_modules/contentful-graph/src/get-relations.js:34:22)
    at types.items.forEach.type (/opt/app/node_modules/contentful-graph/src/content-types-to-model-map.js:17:18)
    at Array.forEach (<anonymous>) } Reason: TypeError: Cannot read property 'name' of undefined
    at getTypeName (/opt/app/node_modules/contentful-graph/src/get-relations.js:13:66)
    at Array.map (<anonymous>)
    at relations.(anonymous function).(anonymous function).validations.reduce (/opt/app/node_modules/contentful-graph/src/get-relations.js:23:56)
    at Array.reduce (<anonymous>)
    at addRelation (/opt/app/node_modules/contentful-graph/src/get-relations.js:21:49)
    at contentType.fields.forEach.field (/opt/app/node_modules/contentful-graph/src/get-relations.js:39:7)
    at Array.forEach (<anonymous>)
    at getRelations (/opt/app/node_modules/contentful-graph/src/get-relations.js:34:22)
    at types.items.forEach.type (/opt/app/node_modules/contentful-graph/src/content-types-to-model-map.js:17:18)
    at Array.forEach (<anonymous>)
Unhandled Rejection: Promise: Promise {
  <rejected> TypeError: Cannot read property 'name' of undefined
    at getTypeName (/opt/app/node_modules/contentful-graph/src/get-relations.js:13:66)
    at Array.map (<anonymous>)
    at relations.(anonymous function).(anonymous function).validations.reduce (/opt/app/node_modules/contentful-graph/src/get-relations.js:23:56)
    at Array.reduce (<anonymous>)
    at addRelation (/opt/app/node_modules/contentful-graph/src/get-relations.js:21:49)
    at contentType.fields.forEach.field (/opt/app/node_modules/contentful-graph/src/get-relations.js:39:7)
    at Array.forEach (<anonymous>)
    at getRelations (/opt/app/node_modules/contentful-graph/src/get-relations.js:34:22)
    at types.items.forEach.type (/opt/app/node_modules/contentful-graph/src/content-types-to-model-map.js:17:18)
    at Array.forEach (<anonymous>) } Reason: TypeError: Cannot read property 'name' of undefined
    at getTypeName (/opt/app/node_modules/contentful-graph/src/get-relations.js:13:66)
    at Array.map (<anonymous>)
    at relations.(anonymous function).(anonymous function).validations.reduce (/opt/app/node_modules/contentful-graph/src/get-relations.js:23:56)
    at Array.reduce (<anonymous>)
    at addRelation (/opt/app/node_modules/contentful-graph/src/get-relations.js:21:49)
    at contentType.fields.forEach.field (/opt/app/node_modules/contentful-graph/src/get-relations.js:39:7)
    at Array.forEach (<anonymous>)
    at getRelations (/opt/app/node_modules/contentful-graph/src/get-relations.js:34:22)
    at types.items.forEach.type (/opt/app/node_modules/contentful-graph/src/content-types-to-model-map.js:17:18)
    at Array.forEach (<anonymous>)
```

**Comment by lotas** [comment]
Hi there!
Thank you for report. It is actually the bug coming from library https://github.com/lotas/contentful-graph/issues/6
And the issue is still not resolved apparently :)

What would have help a lot, is if you could share model json, there is probably some model with a `"name"` property.

**Comment by lotas** [comment]
Hey @tlambrou 
I've released new version of `contentful-graph`: `1.2.0` which should fix the issue.
Commented here: https://github.com/lotas/contentful-graph/issues/6#issuecomment-437627806

Please let me know if this solves your issue.
Thanks

**Comment by tlambrou** [comment]
Hi @lotas.  Thanks for your follow up.  Unfortunately, this did not solve the problem.  Here is the output.

```
➜  contentful-graph-web docker run -it --rm -p 3000:3000 lotas/contentful-graph-web
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm info lifecycle contenful-graph-web@1.0.0~prestart: contenful-graph-web@1.0.0
npm info lifecycle contenful-graph-web@1.0.0~start: contenful-graph-web@1.0.0

> contenful-graph-web@1.0.0 start /opt/app
> node src/server.js

> Ready on http://localhost:3000
Unhandled Rejection: Promise: Promise {
  <rejected> TypeError: Cannot read property 'name' of undefined
    at getTypeName (/opt/app/node_modules/contentful-graph/src/get-relations.js:13:66)
    at Array.map (<anonymous>)
    at relations.(anonymous function).(anonymous function).validations.reduce (/opt/app/node_modules/contentful-graph/src/get-relations.js:23:56)
    at Array.reduce (<anonymous>)
    at addRelation (/opt/app/node_modules/contentful-graph/src/get-relations.js:21:49)
    at contentType.fields.forEach.field (/opt/app/node_modules/contentful-graph/src/get-relations.js:39:7)
    at Array.forEach (<anonymous>)
    at getRelations (/opt/app/node_modules/contentful-graph/src/get-relations.js:34:22)
    at types.items.forEach.type (/opt/app/node_modules/contentful-graph/src/content-types-to-model-map.js:17:18)
    at Array.forEach (<anonymous>) } Reason: TypeError: Cannot read property 'name' of undefined
    at getTypeName (/opt/app/node_modules/contentful-graph/src/get-relations.js:13:66)
    at Array.map (<anonymous>)
    at relations.(anonymous function).(anonymous function).validations.reduce (/opt/app/node_modules/contentful-graph/src/get-relations.js:23:56)
    at Array.reduce (<anonymous>)
    at addRelation (/opt/app/node_modules/contentful-graph/src/get-relations.js:21:49)
    at contentType.fields.forEach.field (/opt/app/node_modules/contentful-graph/src/get-relations.js:39:7)
    at Array.forEach (<anonymous>)
    at getRelations (/opt/app/node_modules/contentful-graph/src/get-relations.js:34:22)
    at types.items.forEach.type (/opt/app/node_modules/contentful-graph/src/content-types-to-model-map.js:17:18)
    at Array.forEach (<anonymous>)
```

**Comment by tlambrou** [comment]
Here is the `package.json`

```
{
  "name": "contenful-graph-web",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "NODE_ENV=development node src/server.js",
    "build": "next build",
    "start": "node src/server.js"
  },
  "keywords": [],
  "author": "Yaraslau Kurmyza <lotask@gmail.com>",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.17.2",
    "contentful-graph": "^1.2.0",
    "express": "^4.15.4",
    "jss": "^8.1.0",
    "jss-preset-default": "^3.0.0",
    "material-ui": "^1.0.0-beta.8",
    "material-ui-icons": "^1.0.0-beta.5",
    "next": "^4.2.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-graph-vis": "^0.1.3",
    "react-json-tree": "^0.10.9",
    "react-jss": "^7.1.0",
    "react-tap-event-plugin": "^2.0.1",
    "react-viewer": "^2.2.6",
    "recompose": "^0.25.0"
  }
}
```

**Comment by lotas** [comment]
@tlambrou Thanks for the update.
Funny thing, I forgot to push latest changes of `contentful-graph-web` with updated dependencies :) Did it now.

Plus, for docker it might be that you have a cached version locally still? 
`docker pull lotas/contentful-graph-web` should show 

```sh
> contenful-graph-web@1.1.0 start /opt/app
```

Locally I run `npx contentful-graph model.json` with downlaoded models, and a broken `.name` thingy and it works fine. 

Would appreciate if you could share the model, or try it locally.

Thanks!

**Comment by tlambrou** [comment]
Great!  That works.  I do get the following error though...
```
docker run -it --rm -p 3000:3000 lotas/contentful-graph-web

> contenful-graph-web@1.1.0 start /opt/app
> node src/server.js

> Ready on http://localhost:3000
Generating /opt/app/static/graphs/tjwbvocp77ui-1542304216557.png
stderr: Error:
stderr: <stdin>: syntax error in line 86 near '"'

child process exited with code 1
```
That keeps repeating for any other images it's generating as well.
